### ISSUE TITLE
Codepen doesn't work

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-number-formatter#1]
As discussed, after clicking on the codepen icon the resultant codepen example doesn't work.

**Comment by nonmetalhail** [comment]
@runn-vermel Looks like it cant find the numbrojs script. I thought I did this correct by including it in the scripts-include property of demo-component-snippet, but guess not. Any ideas on what is missing?

**Comment by runn-vermel** [comment]
added rawgit scripts
