### ISSUE TITLE
Description on index.html incomplete

### ISSUE THREAD

**Issue by mdwragg** [PredixDev/px-number-formatter#2]
As discussed, description of the component is incomplete:

It currently reads:

_px-number-formatter
The px-number-formatter component is..._

**Comment by nonmetalhail** [comment]
Works on my machine! ;)

Have you tried updating and syncing your service worker?

**Comment by mdwragg** [comment]
Works for me too! Might have had an old session knocking around. Apologies.

FYI, service worker shinanigins should be solved after we now correctly invalidate the CDN post-build. But well, that's the idea any way ;-)

💯 @nonmetalhail

**Comment by mdwragg** [comment]
https://www.youtube.com/watch?v=nn2FB1P_Mn8
